# nixpacks.toml

[phases.setup]
# Minta Nixpacks untuk menyediakan PHP 8.3 dan library yang dibutuhkan
nixPkgs = ["php83", "php83Packages.composer", "libjpeg", "libpng", "freetype", "linux.headers"]

[phases.install]
# Perintah untuk menginstal dependensi composer
cmds = ["composer install --no-dev --no-interaction"]

[phases.build]
# Perintah untuk build aset frontend (jika ada)
cmds = ["npm install", "npm run build"]

[start]
# Perintah untuk memulai server, sama seperti di Procfile
cmd = "vendor/bin/heroku-php-apache2 public/"